imixssample-db:
  image: postgres:9.6.1
  environment:
    POSTGRES_PASSWORD: adminadmin
    POSTGRES_DB: workflow-db

imixssample-app:
  image: imixs/imixs-sample
  environment:
    WILDFLY_PASS: adminadmin
    DEBUG: "true"
  ports:
    - "8080:8080"
    - "8787:8787"
    - "9990:9990"
  links: 
    - imixssample-db:imixssample-db
 

    
 