version: "3.6"
services:

  imixssample-db:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: workflow-db
  
  imixssample-app:
    depends_on:
      - imixssample-db
    image: imixs/imixs-jsf-example
    environment:
      TZ: "Europe/Berlin"
    ports:
      - "9080:9080"
      - "9443:9443"
    volumes:
      - ~/git/imixs-jsf-example/src/docker/deployments:/config/dropins/   



    
#  imixsadmin:
#    image: imixs/imixs-admin
#    ports:
#      - "8888:8080"